Put common json format.
Noah0x0/lambda-waterLevelWatcher pull request #7
Opened 2017-08-12 05:32 UTC by Ihara-kenta

### 修正内容
- lambda実行ごとに、`sample_json/wataerLevel{timestamp}.json`にファイル作成する
- APIレスポンスから、下記formatのjsonオブジェクトを生成する
	```
	{
		riverName: '浅野川',
		height: '5.50',
		timestamp: '08月12日 14時10分',
		waterLevel: '0.75',
		dataTrend: '→',
		dataLevel: 0,
		observatory: '金沢市沖橋(諸江)' 
	}
	```

### 参考
https://github.com/Noah0x0/lambda-waterLevelAPI/pull/4

2017-08-12 05:47 UTC, runble1 commented
json形式なので文字列値（riverNameとか）と、値（浅野川）をダブルクォートで囲ってあげてください。

あと、timestampの中身ですが、フォーマットを揃えておいたほうがいいかなって思いました。
例えば以下のような形が一般的ですが、どうしましょう？
※統一したいだけ
ex) "2017-08-12 14:10:00"

2017-08-12 06:43 UTC, Ihara-kenta commented
>json形式なので文字列値（riverNameとか）と、値（浅野川）をダブルクォートで囲ってあげてください。
https://github.com/Noah0x0/lambda-waterLevelWatcher/pull/7/files#diff-168726dbe96b3ce427e7fedce31bb0bcR50
ここで`stringify`を書けているんので、実際にファイルに記載される値はこうなります。
```
{"riverName":"浅野川","height":"5.50","timestamp":"08月12日 15時30分","waterLevel":"0.73","dataTrend":"→","dataLevel":0,"observatory":"金沢市沖橋(諸江)"}
```

2017-08-12 08:04 UTC, runble1 commented
了解です！

timestampの方はどうしましょうか？
フロント側で表示する値そのままがいいですかね？
今後英語表記に統一する場合は 日本語は入れないほうがいいと思ってます。

2017-08-12 08:11 UTC, mesh1neko commented
@runble1 @Ihara-kenta timestampは変換かけたほうがいいかもね。
無難なのはISO8601とか規格に合わせる感じ

2017-08-12 08:13 UTC, mesh1neko commented
FYI
jsでやるときはmoment.jsが便利よ
http://qiita.com/osakanafish/items/5ef636bbcb2c3ef94953

2017-08-12 08:15 UTC, runble1 commented
こうかな
ISO8601
yyyy-MM-ddTHH:mm:ss
ex) 2014-10-10T13:50:40

2017-08-12 08:18 UTC, usagi-f commented
規格に合わせた形で持っていて貰えれば、多言語化も楽です。

moment.jsもいいですし、こんなのもありますね
https://github.com/date-fns/date-fns

https://date-fns.org/v1.28.5/docs/I18n#supported-languages

2017-08-12 08:19 UTC, mesh1nek0x0 approved these changes
+1
日付フォーマット変更は別PRでOK
[![LGTM](http://lgtm.in/p/si2NncyPp)](http://lgtm.in/i/si2NncyPp)

2017-08-12 08:19 UTC, mesh1neko commented on modules/convert.js
> +        const timeLine = data['4357_4_84276000_51']['timeLineData'];
4357_4_84276000_51
は観測所のIDだと思うので、これも定数にしといていいかもね。

2017-08-13 01:31 UTC, Ihara-kenta commented
https://github.com/Noah0x0/lambda-waterLevelWatcher/pull/7/commits/55c7e8e36d46dcd4dbb1b2b046e3c03c2397fad1#diff-e6bb25bff3bc21b5a9e70df5c33976e3R10

こんな形にしてみました、いかがでしょうー？？

2017-08-13 01:54 UTC, mesh1nek0x0 requested changes
コメントしたよー

2017-08-13 01:54 UTC, mesh1neko commented on index.js
> +    const waterLevel = convert.toCommonJson(data);
IMO
formatedJsonの方が意図が伝わりやすいかも

2017-08-13 01:54 UTC, mesh1neko commented on modules/convert.js
> +        const timeStr = dateSplit[0] + '-' +dateSplit[1] + '-' + dateSplit[2] + " " + dateSplit[3] + ":" + dateSplit[4];
FYI
（フォーマットするために先にフォーマットしないといけないなんて...）
最近は文字連結より、Template Literalsの方がスマートかも
cf. https://ja.stackoverflow.com/questions/25425/javascriptjquery%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E6%96%87%E5%AD%97%E5%88%97%E4%B8%AD%E3%81%AB%E5%A4%89%E6%95%B0%E3%82%92%E8%A8%98%E8%BF%B0%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95%E3%81%A3%E3%81%A6%E3%81%82%E3%82%8B%E3%81%A7%E3%81%97%E3%82%87%E3%81%86%E3%81%8B

2017-08-13 07:00 UTC, Ihara-kenta commented on index.js
> +    const waterLevel = convert.toCommonJson(data);
修正しました 🙇 
cb452f9

2017-08-13 07:00 UTC, Ihara-kenta commented on modules/convert.js
> +        const timeStr = dateSplit[0] + '-' +dateSplit[1] + '-' + dateSplit[2] + " " + dateSplit[3] + ":" + dateSplit[4];
必要ないみたいだったので、削除しました。
c511c9c

2017-08-13 07:01 UTC, Ihara-kenta commented
@mesh1neko 確認お願いします〜

2017-08-13 11:22 UTC, mesh1nek0x0 approved these changes

2017-08-13 11:22 UTC, mesh1neko commented
@Ihara-kenta 遅れてすみませんーんOKっす！

2017-08-13 11:23 UTC, mesh1neko commented
[![LGTM](http://lgtm.in/p/mBV1KTa9q)](http://lgtm.in/i/mBV1KTa9q)

2017-08-13 11:26 UTC, merged